### ISSUE TITLE
Switch from /dev/random to /dev/urandom

### ISSUE THREAD

**Issue by kenperkins** [deconst/deploy#121]
I've noticed cases were using /dev/random has resulted in blocking when running deploy on a virtual machine. Based on http://unix.stackexchange.com/a/243218 we should be using /dev/urandom anyway. 

https://github.com/deconst/deploy/blob/master/certificates.yml#L43

**Comment by robb-romans** [comment]
The only instance of this is in the credentials example file command to create an API key, which I don't think is much of a problem. The certificates file has already been changed. I checked the other `deconst-*` repos and don't see it.

```
 Deconst  deploy  find . -type f | xargs grep \/dev\/random
./credentials.example.yml:#  hexdump -v -e '1/1 "%.2x"' -n 128 /dev/random
  Deconst  deploy  find . -type f | xargs grep \/dev\/urandom
./certificates.yml:      head -c 128 /dev/urandom | base64 > certificates/tmppassword &&
```
