### ISSUE TITLE
CoreOS image IDs

### ISSUE THREAD

**Issue by jrperritt** [deconst/deploy#28]
This is what I get when I query the Rackspace images for CoreOS:
| f8f8c267-b3a8-49a9-839f-09977b458762 | CoreOS (Alpha)      | ACTIVE |        |
| 21289dcb-d757-4a45-9058-28151386d155 | CoreOS (Beta)     | ACTIVE |        |
| a202bb99-23d3-4c42-a26f-778c2f974e6a | CoreOS (Stable)    | ACTIVE |        |

Are these supposed to represent those: https://github.com/deconst/deploy/blob/master/vars.yml#L4-7 ?

On either the Stable or Beta image above, `etcd2` wasn't available. CoreOS Alpha always had it though.

**Comment by smashwilson** [comment]
I just pulled them again from Fog and yeah, I see the same ones that you do, now. I wonder if they changed?

I'm running on Beta, but I can try switching to Alpha to see if that helps.

**Comment by smashwilson** [comment]
Fixed in #29.
