### ISSUE TITLE
Research interlock:1.0.0

### ISSUE THREAD

**Issue by etoews** [deconst/deploy#97]
We're planning on using `ehazlett/interlock:1.0.0` for deconst deployment to Carina. It's completely different from the 0.3 days. Need to do a bit of research on it and see how we're going to use it for deconst.

**Comment by mdarby** [comment]
I'm also looking into this now for oauth.getcarina.com migration over to Carina.

https://github.com/getcarina/carina-gem/issues/5

**Comment by etoews** [comment]
So my experiments with `interlock:1.0.0` were revealing. There are a few design issues i'm concerned about.
1. Interlock itself is only configurable via a file or key/value store (but not environment variables)
   https://github.com/ehazlett/interlock/blob/master/docs/configuration.md
2. The extension (nginx/haproxy) config templates are compiled into interlock
   https://github.com/ehazlett/interlock/blob/master/ext/nginx/template.go
3. The reliance on container labels to get stuff into the template
   https://github.com/ehazlett/interlock/blob/master/ext/nginx/generate.go

1 & 2 can potentially be fixed upstream

3 is more of a question for me

The resulting nginx.conf files that interlock was generating weren't working for me.

It could just be that i'm not grokking how the labels are used or why they're so prevalent.

**Comment by etoews** [comment]
I've got an [Interlock Example](https://github.com/everett-toews/interlock-example) for testing it and to demonstrate how far I got with it.

Turns out Interlock doesn't support overlay networking yet. It's coming in [Overlay Network Support](https://github.com/ehazlett/interlock/issues/88).

I've also opened issues for [Configuration via env vars](https://github.com/ehazlett/interlock/issues/92) and [Externalize the extension configuration templates](https://github.com/ehazlett/interlock/issues/91). 

Interlock is good stuff but I think we're going to need to consider alternatives too at this time.
